version: 1.0.{build}
image: Visual Studio 2017
test: off

environment:
  MSYSTEM: MINGW64

artifacts:
  - path: dist\*.zip

install:
- set PATH=C:\msys64\usr\bin;%PATH%
- pacman -S --noconfirm zip unzip

build_script:
- bash -l %APPVEYOR_BUILD_FOLDER%\script\appveyor-build.sh
