version: 1.0.{build}
image: Visual Studio 2017
test: off

environment:
  MSYSTEM: MINGW64

artifacts:
  - path: artifacts\*.zip

cache:
  - C:\projects\Rack

install:
- set PATH=C:\msys64\usr\bin;%PATH%
- set HOME=%APPVEYOR_BUILD_FOLDER%

build_script:
- bash -l script/cibuild

on_finish:
- pwd
