language: cpp
cache:
  directories:
    - /tmp/Rack
before_cache:
    - rm -fr /tmp/Rack/plugins/DHE-Modules
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.2
install:
before_script:
  - git clone https://github.com/VCVRack/Rack.git /tmp/Rack || cd /tmp/Rack && git pull
  - cd /tmp/Rack
  - git branch
  - make dep > /dev/null
  - make
  - rm -rf /tmp/Rack/plugins/DHE-Modules || true
  - cp -r $TRAVIS_BUILD_DIR /tmp/Rack/plugins/DHE-Modules
script:
  - cd /tmp/Rack/plugins/DHE-Modules && VERSION=0.0.0 make dist

